// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: schema_v2.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AmessageV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AmessageV2) Reset() {
	*x = AmessageV2{}
	mi := &file_schema_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AmessageV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmessageV2) ProtoMessage() {}

func (x *AmessageV2) ProtoReflect() protoreflect.Message {
	mi := &file_schema_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmessageV2.ProtoReflect.Descriptor instead.
func (*AmessageV2) Descriptor() ([]byte, []int) {
	return file_schema_v2_proto_rawDescGZIP(), []int{0}
}

func (x *AmessageV2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AmessageV2) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AmessageV2) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_schema_v2_proto protoreflect.FileDescriptor

const file_schema_v2_proto_rawDesc = "" +
	"\n" +
	"\x0fschema_v2.proto\"X\n" +
	"\n" +
	"AmessageV2\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestampB\x06Z\x04./pbb\x06proto3"

var (
	file_schema_v2_proto_rawDescOnce sync.Once
	file_schema_v2_proto_rawDescData []byte
)

func file_schema_v2_proto_rawDescGZIP() []byte {
	file_schema_v2_proto_rawDescOnce.Do(func() {
		file_schema_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_v2_proto_rawDesc), len(file_schema_v2_proto_rawDesc)))
	})
	return file_schema_v2_proto_rawDescData
}

var file_schema_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_schema_v2_proto_goTypes = []any{
	(*AmessageV2)(nil), // 0: AmessageV2
}
var file_schema_v2_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schema_v2_proto_init() }
func file_schema_v2_proto_init() {
	if File_schema_v2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_v2_proto_rawDesc), len(file_schema_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_v2_proto_goTypes,
		DependencyIndexes: file_schema_v2_proto_depIdxs,
		MessageInfos:      file_schema_v2_proto_msgTypes,
	}.Build()
	File_schema_v2_proto = out.File
	file_schema_v2_proto_goTypes = nil
	file_schema_v2_proto_depIdxs = nil
}
